### PR TITLE
IRIS: refactor and closes #296

### LINKED ISSUE #296: Test failure for IRIS.py
Test for IRIS fails when version 0.1.10 of quadprog is installed.

**Current solution**: quadprog must be pinned to 0.1.9.

### PR DESCRIPTION
**Pull request by atravert**
- [x] Closes #296
- [x] Tests added (coverage: 85%)
- [x] `CHANGELOG.md` updated

### CODE REVIEW

**Comment by atravert** [comment]
- there is an issue with the IRIS docstring: validate_docstrings.py does not see the Examples, I don't know why.
-

**Comment by fernandezc** [comment]
>  there is an issue with the IRIS docstring: validate_docstrings.py does not see the Examples, I don't know why.

▶️   Delete the ':' after 'Examples' !   😄 

- You have errors in the `kern` and   `IRIS` docstring examples.

- Also note that you don't need to import NumPy and Spectrochempy for the doctests.  

- One last comment on iris.py:   if methods such as ìsPD` or `Menger` are not intended to be public (accessible by the end user) it would be nice to make them private: def _isPD(... instead of def isPD(... . another positive effect is that sphinx will not generate an API reference html file with unnecessary elements in the API reference and will speed up the doc construction. Do not forget to remove the correspondingt entries in `userguide/reference/api.rst`.

**Comment by atravert** [comment]
Thank you ! -- now I just have a final error related to flake8 and file permission... I guess it is not much important ? 

```
PS C:\Users\traverta\Dropbox\Programmes\spectrochempy> python scripts/validate_docstrings.py spectrochempy.IRIS
Loading SpectroChemPy API: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0/100 [00:01<00:00, 85.66it/s]
SpectroChemPy's API - v.0.3.2.dev34+g47f8e798e
© Copyright 2014-2022 - A.Travert & C.Fernandez @ LCS
spectrochempy.IRIS
1     E902 PermissionError: [Errno 13] Permission denied: 'C:\\Users\\traverta\\AppData\\Local\\Temp\\tmptq577kvx'

################################################################################
######################## Docstring (spectrochempy.IRIS) ########################
################################################################################

Integral inversion solver for spectroscopic data.

Solves integral equations of the first kind of 1 or 2 dimensions, i.e. returns a
distribution f of contributions to 1D ou 2D datasets.

Parameters
-----------
X : NDDataset
    The 1D or 2D dataset on which to perform the IRIS analysis.
K : str or callable or NDDataset
    Kernel of the integral equation. Pre-defined kernels can be chosen among
    `["langmuir", "ca", "reactant-first-order", "product-first-order", "diffusion"]`.
p : Coord or Iterable
    External variable. Must be provided if the kernel is passed as a str or callable.
q : Coord or Iterable of 3 values
    Internal variable. Must be provided if the kernel is passed as a str or callable.
reg_par : None or array_like of two values `[min, max]` or three values `[start, stop, num]`
    Regularization parameter.

Attributes
----------
f : NDDataset
    A 3D/2D dataset containing the solutions (one per regularization parameter).
RSS: array of float
    Residual sums of squares (one per regularization parameter).
SM : array of float
    Values of the regularization constraint (one per regularization parameter).
reg_par : None or array of float
    Values of the regularization parameters.
log : str
    Log of the optimization.
K : NDDataset
    Kernel matrix.
X : NDDataset
    The original dataset.

See Also
--------
    ker : Compute kernel of Fredholm equation of the 1st kind.

Notes
-----
IRIS solves integral equation of the first kind of 1 or 2 dimensions, i.e. finds a distribution
function :math:`f(p)` or :math:`f(c,p)` of contributions to univariate data :math:`a(p)` or multivariate
:math:`a(c, p)` data evolving with an external experimental variable :math:`p` (time, pressure,
temperature, concentration, ...) according to the integral transform:

.. math:: a(c, p) = \int_{min}^{max} k(q, p) f(c, q) dq

.. math:: a(p) = \int_{min}^{max} k(q, p) f(q) dq

where the kernel :math:`k(q, p)` expresses the functional dependence of a single contribution
with respect to the experimental variable :math:`p` and and 'internal' physico-chemical variable :math:`q`
Regularization is triggered when 'reg_param' is set to an array of two or three values.
If 'reg_param' has two values [min, max], the optimum regularization parameter is searched between
:math:`10^{min}` and :math:`10^{max}`. Automatic search of the regularization is made using the
Cultrera_Callegaro algorithm (arXiv:1608.04571v2) which involves the Menger curvature of a circumcircle
and the golden section search method.
If three values are given (`[min, max, num]`), then the inversion will be made for num values
evenly spaced on a log scale between :math:`10^{min}` and :math:`10^{max}`

Examples
--------
>>> X = scp.read("irdata/CO@Mo_Al2O3.SPG")
>>> p = [0.003, 0.004, 0.009, 0.014, 0.021, 0.026, 0.036, 0.051, 0.093, 0.150,
...      0.203, 0.300, 0.404, 0.503, 0.602, 0.702, 0.801, 0.905, 1.004]
>>> iris = scp.IRIS(X[:,2250.0:1960.0], "langmuir", q = [-8, -1, 10])
>>> iris.f
NDDataset: [float64] unitless (shape: (z:1, y:10, x:301))

################################################################################
################################## Validation ##################################
################################################################################

1 Errors found:
        flake8 error: E902 PermissionError: [Errno 13] Permission denied: 'C:\\Users\\traverta\\AppData\\Local\\Temp\\tmptq577kvx'
 


```

**Comment by fernandezc** [comment]
Arnaud, may be you did not see my lasts PR. Actually your test are still executer with quadprog 1.9 because I think you did not update the template for the environment file. See the instructions in this file.

**Comment by fernandezc** [comment]
see here in fact: https://github.com/spectrochempy/spectrochempy/blob/master/environment_dev.yml

**Comment by fernandezc** [comment]
>         flake8 error: E902 PermissionError: [Errno 13] Permission denied: 

I don't know never saw this.
`

**Comment by fernandezc** [comment]
> Arnaud, may be you did not see my lasts PR. Actually your test are still executer with quadprog 1.9 because I think you did not update the template for the environment file. See the instructions in this file.

image

**Comment by atravert** [comment]
understood, thanks !

**Pull request merged**
