### PR TITLE
implement pca.reconstruct()

### PR DESCRIPTION
**Pull request by atravert**
- [x] Tests have been updated
- [X] CHANGELOG updated 
- [X] listed in `docs/userguide/reference/api.rst`.

other changes:
- update pre-commint with last vesion of black (generated an error) 
- reformat .py files accordingly

### CODE REVIEW

**Comment by fernandezc** [comment]
> Hi @fernandezc !
> 
> there is a small problem with some string format that cause an error on 2 tests with python 3.9 only. The same problem causes the error on doc build. I tried few changes but without success. I would be glad if you have some time to look at it...

Hi Arnaud
I think this is due to the fact that you modified the format {:~.3f}  from  {:~.3fK}.   This kind of format iwith a tilde is related to pint, to format the compact representation of units. So either you 
change to {:.3f} or  you  keep the units formatting. Notice that since the last change with pint 0.18, it is advised to use the pretty format : {:~.3fP}.  with P instead of K.

**Comment by fernandezc** [comment]
> > Hi @fernandezc !
> > there is a small problem with some string format that cause an error on 2 tests with python 3.9 only. The same problem causes the error on doc build. I tried few changes but without success. I would be glad if you have some time to look at it...
> 
> Hi Arnaud I think this is due to the fact that you modified the format {:~.3f} from {:~.3fK}. This kind of format iwith a tilde is related to pint, to format the compact representation of units. So either you change to {:.3f} or you keep the units formatting. Notice that since the last change with pint 0.18, it is advised to use the pretty format : {:~.3fP}. with P instead of K.

However, I just checkout your branch Pca but it gives no error locally. I will push it on my side to see if there is an error in Github. For instance test_nmr_context gives an, error with your PR, but I see no change from the master version.

**Comment by fernandezc** [comment]
Well I found the reason for the bug... They updated pint to version 0.19 and this break my code. I will have to investigate this but for know, just pin pint to 0.18 in ci/env_template.yml and then run create_requiirments in scripts to update all requirement and environment files!

**Comment by fernandezc** [comment]
> Well I found the reason for the bug... They updated pint to version 0.19 and this break my code. I will have to investigate this but for know, just pin pint to 0.18 in ci/env_template.yml and then run create_requiirments in scripts to update all requirement and environment files!

I think I have fixed the problem of compatibility (see PR #454).  So you should not need to pin the pint version after I have merged the fix.

**Review by fernandezc — APPROVED** [review]
OK, but I am wondering why you add __init__.py  in test directory.  Do you need to use them as packages?

**Comment by atravert** [comment]
Oups no, i forgot to remove it. This was because vscode doesn't find the tests. I tried this (suggested in some forums) but it didn't work... I will remove it !

Le 6 avril 2022 23:52:24 GMT+02:00, Christian Fernandez ***@***.***> a écrit :
***@***.*** approved this pull request.
>
>OK, but I am wondering why you add init.py in test directory. Do you
>need to use them as packages?
>
>—
>Reply to this email directly, view it on
>GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspectrochempy%2Fspectrochempy%2Fpull%2F453%23pullrequestreview-934187678&data=04%7C01%7Carnaud.travert%40ensicaen.fr%7Cf3a318436dee4e1a921708da1817bcdb%7C430c3e75ff03445fb3f4ae2809a0b10b%7C0%7C0%7C637848787524783132%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=34v8QiArQ0rbTzQ5ZvBQRVcQTowuiTtVFBrl6r6VO1I%3D&reserved=0>,
>or
>unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNBNCW6EHX6GHLZKYGKPN3VDYBRRANCNFSM5SV53BUQ&data=04%7C01%7Carnaud.travert%40ensicaen.fr%7Cf3a318436dee4e1a921708da1817bcdb%7C430c3e75ff03445fb3f4ae2809a0b10b%7C0%7C0%7C637848787524783132%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IPTjVSakvjWjOT%2FhNdhQmewiudmVZ%2BXSV8hS0a1QgDo%3D&reserved=0>.
>You are receiving this because you authored the thread.Message ID:
***@***.***>

-- Envoyé depuis /e/ Mail.

**Pull request merged**
