### PR TITLE
FIX pint compatibility (#490)

### PR DESCRIPTION
**Pull request by atravert**
- [x] Close the #490
- [x] User-visible changes (including notable bug fixes) have been documented in
      `CHANGELOG.md`

### CODE REVIEW

**Comment by atravert** [comment]
@fernandezc : I couldn't manage to print in the output the warning in lines 77-83 of [spectrochempy/__init__.py](https://github.com/spectrochempy/spectrochempy/pull/492/files#diff-086b5541c59b73c40a54b25a3eb42f81044aca9cea6c4dd7d2f71621f3da7383) ,  hence the similar  message lines 36-37 in [spectrochempy/core/units/units.py](https://github.com/spectrochempy/spectrochempy/pull/492/files#diff-e7a8456b9cbae9276c4e4d91b3bbce2c7fcda525d9f7c0b437039ee40af6a001) which appear in the output.  
Any clue ?

**Comment by fernandezc** [comment]
> > @fernandezc : I couldn't manage to print in the output the warning in lines 77-83 of [spectrochempy/**init**.py](https://github.com/spectrochempy/spectrochempy/pull/492/files#diff-086b5541c59b73c40a54b25a3eb42f81044aca9cea6c4dd7d2f71621f3da7383) , hence the similar message lines 36-37 in [spectrochempy/core/units/units.py](https://github.com/spectrochempy/spectrochempy/pull/492/files#diff-e7a8456b9cbae9276c4e4d91b3bbce2c7fcda525d9f7c0b437039ee40af6a001) which appear in the output.
> > Any clue ?
> 
> I think the message is displayed but too early (before the display of the welcome message) thus it is erased. May be the solution could be to make the print at the end of the API loading (at the end of spectrochempy/ api.py file.

But Looking forward it seems that this is already what you do for the pint version checking.

**Comment by atravert** [comment]
Hi @fernandezc ,  

- Finally, I propose to group all checks on pint version in [spectrochempy/core/units/units.py](https://github.com/spectrochempy/spectrochempy/pull/492/files#diff-e7a8456b9cbae9276c4e4d91b3bbce2c7fcda525d9f7c0b437039ee40af6a001). Is it OK for you ? if Yes, I propose to make a new release (0.4.8) after merging this PR.  

- Currently, bugs due to changes in external packages are detected by users or when making pull requests. It would be nic to have automated periodic checks. Github workflows allows this with the [`schedule`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) event. Would you agree to set it on, e.g., each Mon, Wed, Fri ?. This would trigger an alert within ~ 48h after an icompatible upgrade of an external package.

**Comment by fernandezc** [comment]
> Hi @fernandezc ,
> 
> * Finally, I propose to group all checks on pint version in [spectrochempy/core/units/units.py](https://github.com/spectrochempy/spectrochempy/pull/492/files#diff-e7a8456b9cbae9276c4e4d91b3bbce2c7fcda525d9f7c0b437039ee40af6a001). Is it OK for you ? if Yes, I propose to make a new release (0.4.8) after merging this PR.

I agree. Maybe I can do it and write the instructions (because I made an automatic workflow for it last time, but it still needs to be adjusted). If it works, I can write the instructions so you can do it next time. 

> * Currently, bugs due to changes in external packages are detected by users or when making pull requests. It would be nic to have automated periodic checks. Github workflows allows this with the [`schedule`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) event. Would you agree to set it on, e.g., each Mon, Wed, Fri ?. This would trigger an alert within ~ 48h after an icompatible upgrade of an external package.

Ok, good idea. I would suggest doing a nightly build (so every night) to further decrease the detection time.

**Comment by atravert** [comment]
Thank you, yes please go ahead with the with the release 👍

**Comment by atravert** [comment]
Hi @fernandezc, did you have time to update the workflow to make a new release ?   It is quite urgent to make a new one as the stable release is not working with the current pint version. Let me know if I can help.

**Comment by fernandezc** [comment]
Hi Arnaud,
I have just released the 0.4.8 release. The conda package should appear at the end of the build. 

For the next time, as it seems to work, I give you the instructions:

In the Action tab of GitHub, select:
- Create a new draft release. 
This workflow has a workflow_dispacth eent so you can run it manually.
-> Run workflow. 
Choose the master branch, don't forget to enter the new release tag (0.4.9 or higher next time).
This automatically creates a PR from a release/<tag> branch.
Bypass the requirements (since all the tests have already been done on master) and thus force the merge to close the PR.

Then in the Action tab, click on the workflow publish a draft release.  Choose the target: master. 

Zenodo is normally updated, as well as the citation.cff file and after the end of the build pypi and conda are updated.

That's it!

**Comment by fernandezc** [comment]
@atravert (not sure you are noticed on a closed PR discussion)

**Comment by atravert** [comment]
I was !  Meci beaucoup Christian. Il faudrait qu'on fasse une visio à l'occasion :-)

Le 1 novembre 2022 11:47:10 GMT+01:00, Christian Fernandez ***@***.***> a écrit :
***@***.***<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fatravert&data=05%7C01%7Carnaud.travert%40ensicaen.fr%7C0487ed3299de4417d62e08dabbf66e58%7C430c3e75ff03445fb3f4ae2809a0b10b%7C0%7C0%7C638028964335625847%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FuDOiEwAQdEx%2BNoESOEUKhHLfysVtZT7iK9B0kNeVfc%3D&reserved=0> (not sure you are noticed on a closed PR discussion)
>
>—
>Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspectrochempy%2Fspectrochempy%2Fpull%2F492%23issuecomment-1298343007&data=05%7C01%7Carnaud.travert%40ensicaen.fr%7C0487ed3299de4417d62e08dabbf66e58%7C430c3e75ff03445fb3f4ae2809a0b10b%7C0%7C0%7C638028964335625847%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OV5zM9OK9xWNBjwc97d8PehWFg9zfj%2FJKH%2B9mRaRaRc%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNBNCQROWWVLEHHZIBWP33WGDYK5ANCNFSM6AAAAAARPQRNEQ&data=05%7C01%7Carnaud.travert%40ensicaen.fr%7C0487ed3299de4417d62e08dabbf66e58%7C430c3e75ff03445fb3f4ae2809a0b10b%7C0%7C0%7C638028964335625847%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ffEWpCFQb1TdnYurGMiLtf4VCfv35Xg67lAbZvkVnQQ%3D&reserved=0>.
>You are receiving this because you were mentioned.Message ID: ***@***.***>

-- Envoyé depuis /e/ Mail.

**Pull request merged**
