### PR TITLE
Feature/readers

### PR DESCRIPTION
**Pull request by atravert**
Add examples and tests for omnic series and dso readers (should close issue #185)

### CODE REVIEW

**Comment by fernandezc** [comment]
Arnaud, je t'ai envoyé un fichier .travis.yml correct pour que ton pull request puisse passer. pour le moment il ne dépassera pas cette étape.

**Comment by atravert** [comment]
I have added a commit with the updated .travis.yml file

**Comment by atravert** [comment]
Travis fails on the following tests: test_read_matlab() and test_read_caroucell() while they run fine on my machine (python 3.7). 
I suppose that I should run these tests locally with python 3.6 and 3.9. Then what is the easiest:
- change python version of my current conda env ? 
- or create 3 envs 3.6 / 3.7 / 3.9 and install spectrochempy on them ? 
- or another solution  ?

**Comment by atravert** [comment]
Travis fails on the following tests: test_read_matlab() and test_read_caroucell() while they run fine on my machine (python 3.7). 
I suppose that I should run these tests locally with python 3.6 and 3.9. Then what is the easiest:
- change python version of my current conda env ? 
- or create 3 envs 3.6 / 3.7 / 3.9 and install spectrochempy on them ? 
- or another solution  ?

**Comment by fernandezc** [comment]
> Travis fails on the following tests: test_read_matlab() and test_read_caroucell() while they run fine on my machine (python 3.7).
> I suppose that I should run these tests locally with python 3.6 and 3.9. Then what is the easiest:
> 
> * change python version of my current conda env ?
> * or create 3 envs 3.6 / 3.7 / 3.9 and install spectrochempy on them ?
> * or another solution  ?

May be the simplest (because I don't think the problem is the python version is to add travis testing for 3.7, they run in parallel so there is not cost for us. 

(Be careful with the indentation - use space not tab) 

In travis.yml: 
```yaml
jobs:
  fast_finish: true
  include:
    - stage: tests
      name: py3.6
      if: type == pull_request or branch NOT IN (master)
      env:
      - TEST=true
      - CONDAPY=3.6
```
add this here ....
```yaml
   - name: py3.7
      if: type == pull_request or branch NOT IN (master)
      env:
      - TEST=true
      - CONDAPY=3.7
```
then the rest is unchanged 
```yaml 
    - name: py3.9
      if: type == pull_request or branch NOT IN (master)
      env:
      - TEST=true
      - CONDAPY=3.9
    - name: conda-deploy
      if: type == pull_request AND branch IN (master, develop) OR tag =~ /^\d{1,2}\.\d{1,2}\.\d{1,2}(.rc\d+)?$/
      env:
      - DEPLOY=true
      - CONDAPY=3.8
    - stage: build-docs
      if: type != pull_request AND (branch IN (master, develop) OR tag =~ /^\d{1,2}\.\d{1,2}\.\d{1,2}(.rc\d+)?$/)
      env:
      - BUILDOCS=true
      - CONDAPY=3.8
```

**Comment by fernandezc** [comment]
Your travis file do not work because``` - name:``` if well aligned!

**Comment by fernandezc** [comment]
> Your travis file do not work because` - name:` if well aligned!

Actually this is my fault!   just add a space before the dash

**Comment by fernandezc** [comment]
+1 now it works

**Comment by atravert** [comment]
PR#209: data and tests for srs and dso readers is OK now.

For the record: the order in which read_dir() reads the files and/or appends the datatsets in the final list can change depending on th python implementation. For instance, same order on my configuration (python 3.7) and Travis tests python 3.6 ; different order for Travis tests 3.7 and 3.9....  This is not very important but we should either mention it in the docstring or ensure a constant order (e.g. returning the datasets by the alphabetic order of the filenames) ?

**Comment by fernandezc** [comment]
This is due to a change in the implementation of dictionaries since 3.7. Now the order of the insertion of keys is guaranteed. It was not the case before. To keep the compatibilities 3.6,/3.7 it would be possible to use [ordereddict](https://docs.python.org/fr/3.6/library/collections.html#collections.OrderedDict) instead of dict.

**Comment by atravert** [comment]
OK. Then let it go :-)

Le 09/02/2021 à 00:16, Christian Fernandez a écrit :

**Pull request merged**
